Project.create("name"=>"Nazwa_nr_1", "description"=>"Opis_nr_1")
Project.create("name"=>"Nazwa_nr_2", "description"=>"Opis_nr_2")
Project.create("name"=>"Nazwa_nr_3", "description"=>"Opis_nr_3")
Project.create("name"=>"Nazwa_nr_4", "description"=>"Opis_nr_4")
Project.create("name"=>"Nazwa_nr_5", "description"=>"Opis_nr_5")
Project.create("name"=>"Nazwa_nr_6", "description"=>"Opis_nr_6")
Project.create("name"=>"Nazwa_nr_7", "description"=>"Opis_nr_7")
Project.create("name"=>"Nazwa_nr_8", "description"=>"Opis_nr_8")
Project.create("name"=>"Nazwa_nr_9", "description"=>"Opis_nr_9")
ToDoList.create("name"=>"Moja_todolista_1", "project_id"=>1)
ToDoList.create("name"=>"Moja_todolista_2", "project_id"=>2)
ToDoList.create("name"=>"Moja_todolista_3", "project_id"=>2)
Task.create("name"=>"Moje_imie_nr_1", "description"=>"Opis mojego taska nr 1", "due_date"=>"2020-09-18", "position"=>4, "done_status"=>true, "to_do_list_id"=>2)
Task.create("name"=>"Moje_imie_nr_2", "description"=>"Opis mojego taska nr 2", "due_date"=>"2020-03-22", "position"=>6, "done_status"=>false, "to_do_list_id"=>2)
Comment.create("username"=>"Imie commenta nr 1", "post_date"=>"2010-01-11", "page"=>4, "body"=>"jakiescialo1", "file"=>"nazwa_testowa_1", "to_do_list_id"=>2)
Comment.create("username"=>"Imie commenta nr 2", "post_date"=>"2010-02-12", "page"=>5, "body"=>"jakiescialo2", "file"=>"nazwa_testowa_2", "to_do_list_id"=>2)
Comment.create("username"=>"Imie commenta nr 3", "post_date"=>"2010-03-13", "page"=>6, "body"=>"jakiescialo3", "file"=>"nazwa_testowa_3", "to_do_list_id"=>2)
Comment.create("username"=>"Imie commenta nr 4", "post_date"=>"2010-04-14", "page"=>7, "body"=>"jakiescialo4", "file"=>"nazwa_testowa_4", "to_do_list_id"=>2)
Comment.create("username"=>"Imie commenta nr 5", "post_date"=>"2010-05-15", "page"=>8, "body"=>"jakiescialo5", "file"=>"nazwa_testowa_5", "to_do_list_id"=>2)

