Project.create("name"=>"Nazwa_nr_1", "description"=>"Opis_nr_1")
Project.create("name"=>"Nazwa_nr_2", "description"=>"Opis_nr_2")
Project.create("name"=>"Nazwa_nr_3", "description"=>"Opis_nr_3")
Project.create("name"=>"Nazwa_nr_4", "description"=>"Opis_nr_4")
Project.create("name"=>"Nazwa_nr_5", "description"=>"Opis_nr_5")
Project.create("name"=>"Nazwa_nr_6", "description"=>"Opis_nr_6")
Project.create("name"=>"Nazwa_nr_7", "description"=>"Opis_nr_7")
Project.create("name"=>"Nazwa_nr_8", "description"=>"Opis_nr_8")
Project.create("name"=>"Nazwa_nr_9", "description"=>"Opis_nr_9")
ToDoList.create("name"=>"Moja_todolista_1", "project_id"=>1)
ToDoList.create("name"=>"Moja_todolista_2", "project_id"=>2)
ToDoList.create("name"=>"Moja_todolista_3", "project_id"=>2)
Task.create("name"=>"Moje_imie_nr_1", "description"=>"Opis mojego taska nr 1", "due_date"=>"2020-09-18", "position"=>4, "done_status"=>true, "to_do_list_id"=>2)
Task.create("name"=>"Moje_imie_nr_2", "description"=>"Opis mojego taska nr 2", "due_date"=>"2020-03-22", "position"=>6, "done_status"=>false, "to_do_list_id"=>2)
Comment.create("body"=>"Moj_maly_komentarz_1", "task_id"=>2)
Comment.create("body"=>"Moj_maly_komentarz_2", "task_id"=>2)
Comment.create("body"=>"Moj_maly_komentarz_1", "task_id"=>2)
